version: '3.1'
services:
  java-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: java-api
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql:8.0.31
    volumes:
      - dbbase:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ticket_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    container_name: mysqldb

volumes:
  dbbase: